config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  get '/allstores', to: "stores#all"
  get '/stores/:id/products/new', to: "products#new"
  resources :stores, only: [:index, :new, :create, :show]
  resources :products, only: [:show, :create]
  post '/products/:id/buy', to: "products#buy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :stores
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def owner?(store)
    store.customer == self
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store

  def sell
    self.quantity-=1
  end

end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :customer
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product= Product.new
    @id = params[:id]
  end

  def create
    @product = Product.new(params.require(:product).permit(:name, :value,:description ,:store_id, :quantity))
    if @product.save
      flash[:notice] = 'Produto adicionado com sucesso!'
      redirect_to @product
    else
      flash[:notice] = 'Não foi possível adicionar o produto'
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
    @stores = current_customer.stores
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.new(params.require(:store).permit(:name, :slogan))
    @store.customer = current_customer
    if @store.save
      flash[:notice] = 'Loja criada com sucesso!'
      redirect_to @store
    else
      flash[:notice] = 'Não foi possível criar a loja.'
      render :new
    end
  end

  def all
    @stores = Store.all
  end

  def show
    @store = Store.find(params[:id])
    @products = @store.products
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/home/index.html.erb
<div class="container">
<div class="text-center">
<h1>Bem Vindo ao Gecommerce!</h1>
<p>Sua plataforma fácil de Ecommerce.</p>
</div>
<img src="images/ecommerce.jpg" class="img img-fluid rounded" />
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gecommerce</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Menu navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Gecommerce</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to 'Início', root_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= allstores_path%>">Lojas</a>
          </li>
          <% if customer_signed_in? %>
          <li class="nav-item">
            <a class="nav-link" href="<%=stores_path%>">Minhas Lojas</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Meus Pedidos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%=destroy_customer_session_path%>" data-method="DELETE">Sair</a>
          </li>
        <% else %>
          <li class="nav-item">
            <a class="nav-link" href="<%=new_customer_session_path%>">Entrar</a>
          </li>
        <% end %>
        </ul>
      </div>
    </nav>
    <!-- fim menu -->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<% @products.each do |product| %>
  Nome: <%= product.name %>
  Descrição: <%= product.value %><br>
<% end %>

app/views/products/new.html.erb
Adicione produtos a sua loja!
<%= form_for @product, html: {multipart: true}  do |f| %>
    <%= f.label :name%>
    <%= f.text_field :name%>

    <%= f.label :description%>
    <%= f.text_field :description%>

    <%= f.label :quantity%>
    <%= f.text_field :quantity%>

    <%= f.label :value%>
    <%= f.text_field :value%>

    <%= f.hidden_field :store_id, :value => @id %>

    <%= f.submit "Enviar"%>
<% end %>

app/views/products/show.html.erb
<div class="text-center">
<table class="table">
  <tr>
    <td>Nome: <%= @product.name %></td>
  </tr>
  <tr>
    <td>Descrição: <%= @product.description %></td>
  </tr>
  <tr>
    <td>Valor: <%= @product.value %></td>
  </tr>
  <tr>
    <td>Quantidade: <%= @product.quantity %></td>
  </tr>
</table>
</div>

app/views/stores/all.html.erb
<div class="container">
  <div class="text-center">
    <h1>Todas as Lojas</h1>
    <% if !@stores.empty? %>
      <table class="table table-striped table-bordered">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Loja</th>
          </tr>
        </thead>
        <tbody>
          <% @stores.each do |store| %>
            <tr>
              <td><%=link_to store.name, store_path(store), class: "btn btn-warning"%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>Nenhuma loja cadastrada!</p>
    <% end %>

    <p><%=link_to "Criar Loja", new_store_path ,class: "btn btn-primary"%></p>
  </div>
</div>

app/views/stores/index.html.erb
<div class="container">
  <div class="text-center">
    <h1>Minhas Lojas</h1>
    <% if !@stores.empty? %>
      <table class="table table-striped table-bordered">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Loja</th>
          </tr>
        </thead>
        <tbody>
          <% @stores.each do |store| %>
            <tr>
              <td><%=link_to store.name, store_path(store), class: "btn btn-warning"%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>Nenhuma loja cadastrada!</p>
    <% end %>

    <p><%=link_to "Criar Loja", new_store_path ,class: "btn btn-primary"%></p>
  </div>
</div>

app/views/stores/new.html.erb
Crie sua loja!
<%= form_for @store, html: {multipart: true}  do |f| %>
    <%= f.label :name%>   
    <%= f.text_field :name%>

    <%= f.label :slogan%>
    <%= f.text_field :slogan%>

    <%= f.submit "Enviar"%>
<% end %>

app/views/stores/show.html.erb
<div class="container">
  <div class="text-center">
    <h1><%= @store.name %></h1>
    <p><%= @store.slogan %></p>

    <% if !@products.empty? %>
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Produto</th>
            <th scope="col">Quantidade</th>
            <th scope="col">Valor</th>
            <% if current_customer && !current_customer.owner?(@store) || !current_customer%>
              <th scope="col"> </th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @products.each do |product| %>
            <tr>
              <td><%= link_to product.name, product_path(product) %></td>
              <td><%= product.quantity %>
              <td>R$ <%= product.value %></td>
              <% if current_customer && !current_customer.owner?(@store) || !current_customer%>
                <td><%= link_to 'Comprar', product_path(product), class: "btn btn-primary" %> </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>Nenhum produto cadastrado!</p>
    <% end %>

    <%= link_to 'Adicionar Produto', "/stores/#{@store.id}/products/new" %>
  </div>
</div>